
branches:
  only:
    - master
    - develop
install:
 - source ./support/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
before_script:
# install iodhbwm bundle
  - source support/create-fake-tds.sh
  - mkdir -p ~/texmf/
  - latestTag=$(git describe --tags)
  - yes | cp -rf release/$latestTag-tds/* ~/texmf/
  - mktexlsr ~/texmf
script:
# Prefix command with travis_wait x so it times out after 3 mins
# Run basic example
  - cd doc/examples/basic-usage
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-example
  - travis_wait 3 biber iodhbwm-example
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-example
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-example
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-print
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-auto-sections
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-auto-sections
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-auto-sections-with-abstract
  - travis_wait 3 biber iodhbwm-auto-sections-with-abstract
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-auto-sections-with-abstract
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-auto-sections-with-abstract
# Run listings example
  - cd ../listings
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-listings
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-listings
# Run titlepage example
  - cd ../titlepages
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-custom-titlepage
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-titlepage-logo
# Run reference example
  - cd ../references
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references
  - travis_wait 3 biber iodhbwm-references
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references-custom-style
  - travis_wait 3 biber iodhbwm-references-custom-style
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references-custom-style
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references-custom-style
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references-footcite
  - travis_wait 3 biber iodhbwm-references-footcite
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references-footcite
  - travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error iodhbwm-references-footcite
after_script:
  - rm -r ~/texmf/tex/latex/*
