
branches:
  only:
    - master
    - develop
install:
 - source ./support/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
# Prefix command with travis_wait x so it times out after 3 mins
- travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error ./examples/iodhbwm-example.tex
- travis_wait 3 pdflatex -interaction=nonstopmode -halt-on-error ./examples/iodhbwm-example.tex
